### ISSUE TITLE
Make new npm release to fix npm audit severity vulnerabilities

### ISSUE THREAD

**Issue by de-dan** [h2non/audioconcat#11]
Hi,
the currently released version of audioconcat@0.1.3 on npm uses lodash.merge@^3.0.0, which is marked by npm audit as possible high security risk. I have seen, you already updated the package.json with the new version of lodash.merge, which is fine with npm audit.
It would be nice, if you could release a new version of audioconcat, to get rid of this warning.

Thank you in advance!

**Comment by h2non** [comment]
`v0.1.4` is now available on npm: https://www.npmjs.com/package/audioconcat
